### ISSUE TITLE
Not connecting/working

### ISSUE THREAD

**Issue by remy** [EarMaster/home-assistant-idotmatrix#1]
Hi there, appreciate the (fairly) new integration. I had been keeping an eye out and had my own rudimentary [web version](https://idot-matrix.netlify.app/) (Chrome only - as it requires web Bluetooth).

Anyway, I can't get this integration to work at all… hoping I could debug and help fix?

I've got a lot of errors and wasn't sure which errors would be most useful (or even irrelevant).

Log errors:

```
Logger: homeassistant.setup
Source: setup.py:278
First occurred: 8:33:35 AM (1 occurrence)
Last logged: 8:33:35 AM
Setup failed for custom integration 'idotmatrix': No setup or config entry setup function defined. 
```

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:335
First occurred: 8:43:28 AM (1 occurrence)
Last logged: 8:43:28 AM
Detected that custom integration 'idotmatrix' sets option flow config_entry explicitly, which is deprecated at custom_components/idotmatrix/config_flow.py, line 194: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'idotmatrix' custom integration 
```

```
Error scanning for devices: 'str' object has no attribute 'name'
4:21:02 PM - (ERROR) iDotMatrix Display (custom integration) - message first occurred at 3:03:26 PM and shows up 3 times
```

Screenshots of UI errors:

<img width="479" alt="Image" src="https://github.com/user-attachments/assets/8fdf918d-b7ec-4fbd-9f44-ae3c003150e1" />

I got this after I click ok the modal above, even though HA has been restarted.

<img width="558" alt="Image" src="https://github.com/user-attachments/assets/55c2918a-8ae2-406c-b32a-1943d4049bbc" />

I should add that I can connect to the idot matrix (both on my web version) and the android app via bluetooth, and HA can see the device:

<img width="1385" alt="Image" src="https://github.com/user-attachments/assets/e0c3f098-9503-4deb-8390-960ff641c9b7" />

Any ideas?

**Comment by tigers75** [comment]
I’m experiencing the same problem: it looks like a problem with the base config, not with finding the device. I tried rebooting it and I’m sure it’s not connected to anything else (turned off BT in the only phone I ever used to control the panel and restarted it): scan fails and manual adding with the MAC address doesn’t work either.

Any clue on what I should try?

**Comment by JoshAtticus** [comment]
This integration is AI generated garbage. The README says it's mainly AI generated, and it's completely non-functional. No clue how it got onto the main HACS repo.
